# BASIC AUTH
proxy:
  ### PERSONALIZATION ###
  title: "ShinyStudio"
  hide-navbar: false
  ### AUTHENTICATION ###
  admin-groups: ['developers', 'administrators']
  authentication: simple
  users:
  - name: admin
    password: administrator
    groups: administrators
  - name: dev
    password: developer
    groups: developers
  - name: user
    password: user
    groups: viewers
  ### DANGER ZONE ###
  port: 8080 # LEAVE ME ALONE
  landing-page: /
  logo-url: file:///opt/shinyproxy/templates/grid-layout/assets/img/logo.png
  favicon-path: /opt/shinyproxy/templates/grid-layout/assets/img/logo.png
  template-path: ./templates/grid-layout
  container-wait-time: 30000
  heartbeat-rate: 15000
  heartbeat-timeout: 120000
  usage-stats-url: http://influxdb:8086/write?db=shinyproxy_usagestats
  docker:
    internal-networking: true
  specs:
    - id: reports
      display-name: Apps & Reports
      logo-url: 'fas fa-chart-line'
      container-image: "${SITE_NAME}_shinystudio:${TAG}"
      container-cmd: [ "shiny-server" ]
      container-network: "${SITE_NAME}_default"
      container-volumes:
        - "${CONTENT_PATH}/sites/${SITE_NAME}/_apps:/srv/shiny-server:z"
        - "${SITE_NAME}_r_libraries:/r-libs"
        - "${SITE_NAME}_py_environment:/conda3"
        - "${SITE_NAME}_pwsh_modules:/home/#{proxy.userId}/.local/share/powershell/Modules"
      access-groups: [ 'administrators', 'developers', 'viewers' ]
      container-env:
        USER: "#{proxy.userId}"
        USERID: ${USERID}
    - id: documents
      display-name: Documents
      logo-url: 'fas fa-file-alt'
      container-image: "${SITE_NAME}_shinystudio:${TAG}"
      container-cmd: [ "shiny-server" ]
      container-network: "${SITE_NAME}_default"
      container-volumes:
        - "${CONTENT_PATH}/sites/${SITE_NAME}/_docs:/srv/shiny-server:z"
        - "${SITE_NAME}_r_libraries:/r-libs"
        - "${SITE_NAME}_py_environment:/conda3"
        - "${SITE_NAME}_pwsh_modules:/home/#{proxy.userId}/.local/share/powershell/Modules"
      access-groups: [ 'administrators', 'developers', 'viewers' ]
      container-env:
        USER: "#{proxy.userId}"
        USERID: ${USERID}
    - id: personal
      display-name: Personal
      logo-url: 'far fa-folder-open'
      container-image: "${SITE_NAME}_shinystudio:${TAG}"
      container-cmd: [ "shiny-server" ]
      container-network: "${SITE_NAME}_default"
      container-volumes:
        - "${CONTENT_PATH}/users/#{proxy.userId}:/srv/shiny-server:z"
        - "${SITE_NAME}_r_libraries:/r-libs"
        - "${SITE_NAME}_py_environment:/conda3"
        - "${SITE_NAME}_pwsh_modules:/home/#{proxy.userId}/.local/share/powershell/Modules"
      access-groups: [ 'administrators', 'developers', 'viewers' ]
      container-env:
        USER: "#{proxy.userId}"
        USERID: ${USERID}
    - id: rstudio
      display-name: RStudio
      logo-url: 'fab fa-r-project'
      container-image: "${SITE_NAME}_shinystudio:${TAG}"
      container-cmd: [ "rstudio" ]
      container-network: "${SITE_NAME}_default"
      container-volumes:
        - "${CONTENT_PATH}/sites/${SITE_NAME}:/home/#{proxy.userId}/__ShinyStudio__:z"
        - "${CONTENT_PATH}/users/#{proxy.userId}:/home/#{proxy.userId}/__Personal__:z"
        - "${CONTENT_PATH}/users/#{proxy.userId}/.rstudio:/home/#{proxy.userId}/.rstudio/monitored/user-settings:z"
        - "${SITE_NAME}_r_libraries:/r-libs"
        - "${SITE_NAME}_py_environment:/conda3"
        - "${SITE_NAME}_pwsh_modules:/home/#{proxy.userId}/.local/share/powershell/Modules"
      container-env:
        USER: "#{proxy.userId}"
        USERID: ${USERID}
      description: Full Screen
      port: 8787
      access-groups: [ 'developers' ]
    - id: rstudio-admin
      display-name: RStudio
      logo-url: 'fab fa-r-project'
      container-image: "${SITE_NAME}_shinystudio:${TAG}"
      container-cmd: [ "rstudio" ]
      container-network: "${SITE_NAME}_default"
      container-volumes:
        - "${CONTENT_PATH}:/home/#{proxy.userId}/__ShinyStudio__:z"
        - "${CONTENT_PATH}/users/#{proxy.userId}:/home/#{proxy.userId}/__Personal__:z"
        - "${CONTENT_PATH}/users/#{proxy.userId}/.rstudio:/home/#{proxy.userId}/.rstudio/monitored/user-settings:z"
        - "${SITE_NAME}_r_libraries:/r-libs"
        - "${SITE_NAME}_py_environment:/conda3"
        - "${SITE_NAME}_pwsh_modules:/home/#{proxy.userId}/.local/share/powershell/Modules"
      container-env:
        USER: "#{proxy.userId}"
        USERID: ${USERID}
        SITE_NAME: ${SITE_NAME}
      description: Full Screen
      port: 8787
      access-groups: [ 'administrators' ]
    - id: vscode
      display-name: Visual Studio Code
      logo-url: 'fas fa-terminal'
      container-image: "${SITE_NAME}_shinystudio:${TAG}"
      container-cmd: [ "vscode" ]
      container-network: "${SITE_NAME}_default"
      container-volumes:
        - "${CONTENT_PATH}/sites/${SITE_NAME}:/home/#{proxy.userId}/__ShinyStudio__:z"
        - "${CONTENT_PATH}/users/#{proxy.userId}:/home/#{proxy.userId}/__Personal__:z"
        - "${CONTENT_PATH}/users/#{proxy.userId}/.vscode:/home/#{proxy.userId}/.local/share/code-server:z"
        - "${SITE_NAME}_r_libraries:/r-libs"
        - "${SITE_NAME}_py_environment:/conda3"
        - "${SITE_NAME}_pwsh_modules:/home/#{proxy.userId}/.local/share/powershell/Modules"
      container-env:
        USER: "#{proxy.userId}"
        USERID: ${USERID}
      description: Full Screen
      port: 8080
      access-groups: [ 'developers' ]
    - id: vscode-admin
      display-name: Visual Studio Code
      logo-url: 'fas fa-terminal'
      container-image: "${SITE_NAME}_shinystudio:${TAG}"
      container-cmd: [ "vscode" ]
      container-network: "${SITE_NAME}_default"
      container-volumes:
        - "${CONTENT_PATH}:/home/#{proxy.userId}/__ShinyStudio__:z"
        - "${CONTENT_PATH}/users/#{proxy.userId}:/home/#{proxy.userId}/__Personal__:z"
        - "${CONTENT_PATH}/users/#{proxy.userId}/.vscode:/home/#{proxy.userId}/.local/share/code-server:z"
        - "${SITE_NAME}_r_libraries:/r-libs"
        - "${SITE_NAME}_py_environment:/conda3"
        - "${SITE_NAME}_pwsh_modules:/home/#{proxy.userId}/.local/share/powershell/Modules"
      container-env:
        USER: "#{proxy.userId}"
        USERID: ${USERID}
        SITE_NAME: ${SITE_NAME}
      description: Full Screen
      port: 8080
      access-groups: [ 'administrators' ]
