version: '3.5'

services:
  shinystudio:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - influxdb
    networks:
      - shinystudio-net
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './configs/odbc/odbcinst.ini:/etc/odbcinst.ini:z'
      - './configs/odbc/odbc.ini:/etc/odbc.ini:z'
      - './configs/vscode/User/settings.json:/code-server-template/User/settings.json:z'
      - './configs/vscode/User/snippets:/code-server-template/User/snippets:z'
      - './configs/shinyproxy/background.png:/opt/shinyproxy/templates/grid-layout/assets/img/background.png:z'
      - "${SITECONFIG}:/opt/shinyproxy/application.yml:z"
    environment:
      - APPLICATION_LOGS_TO_STDOUT=false
      - MOUNTPOINT=${MOUNTPOINT}

  influxdb:
    image: influxdb
    container_name: shinystudio_influxdb
    restart: always
    networks:
      - shinystudio-net
    ports:
      - 8086:8086
    volumes:
      - './configs/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:z'
      - 'influxdb_data:/var/lib/influxdb'
    environment:
      - INFLUXDB_DB=shinyproxy_usagestats
      - INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=hLUCoz0gtymi
      - INFLUXDB_REPORTING_DISABLED=true

volumes:
  influxdb_data:

networks:
  shinystudio-net:
    name: shinystudio-net
  default:
     external:
      name: shinystudio-net
