# BASIC AUTH
proxy:
  ### PERSONALIZATION ###
  title: ShinyStudio:${SITEID}
  hide-navbar: false
  logo-url: file:///opt/shinyproxy/templates/2col/assets/img/shinystudio.png
  favicon-path: /opt/shinyproxy/templates/2col/assets/img/shinystudio.png
  template-path: ./templates/2col # or [1-2]col
  ### AUTHENTICATION ###
  admin-groups: ['admins', 'superadmins']
  authentication: simple
  users:
  - name: superadmin
    password: superadmin
    groups: superadmins
  - name: admin
    password: admin
    groups: admins
  - name: user
    password: user
    groups: readers
  ### DANGER ZONE ###
  port: 8080 # don't change!
  landing-page: /
  heartbeat-rate: 15000
  heartbeat-timeout: 120000
  usage-stats-url: http://influxdb:8086/write?db=shinyproxy_usagestats
  usage-stats-username: 'admin'
  usage-stats-password: 'hLUCoz0gtymi'
  docker:
    internal-networking: true
  specs:
    - id: reports
      display-name: Apps & Reports
      description: View Shiny applications and reports.
      container-image: shinystudio_rshiny_rstudio
      container-network: shinystudio-net
      container-volumes:
        - "${MOUNTPOINT}/${DESTSITE}/_apps:/srv/shiny-server:z"
        - 'r_libraries:/r-libs'
      access-groups: [ 'superadmins', 'admins', 'readers' ]
      container-env:
        USER: "#{proxy.userId}"
        USERID: ${USERID}
    - id: documents
      display-name: Documents
      description: View shared documentation.
      container-image: shinystudio_rshiny_rstudio
      container-network: shinystudio-net
      container-volumes:
        - "${MOUNTPOINT}/${DESTSITE}/_docs:/srv/shiny-server:z"
        - 'r_libraries:/r-libs'
      access-groups: [ 'superadmins', 'admins', 'readers' ]
      container-env:
        USER: "#{proxy.userId}"
        USERID: ${USERID}
    - id: content
      display-name: Site Content
      description: View site content.
      container-image: shinystudio_rshiny_rstudio
      container-network: shinystudio-net
      container-volumes:
        - "${MOUNTPOINT}/${DESTSITE}:/srv/shiny-server:z"
        - 'r_libraries:/r-libs'
      access-groups: [ 'admins' ]
      container-env:
        USER: "#{proxy.userId}"
        USERID: ${USERID}
    - id: contentadmin
      display-name: All Content
      description: View content from all sites.
      container-image: shinystudio_rshiny_rstudio
      container-network: shinystudio-net
      container-volumes:
        - "${MOUNTPOINT}:/srv/shiny-server:z"
        - 'r_libraries:/r-libs'
      access-groups: [ 'superadmins' ]
      container-env:
        USER: "#{proxy.userId}"
        USERID: ${USERID}
    - id: rstudio
      display-name: RStudio
      description: Create interactive apps and docs RStudio.
      container-image: shinystudio_rshiny_rstudio
      container-cmd: ["/start.sh", "rstudio"]
      container-network: shinystudio-net
      container-volumes:
        - "${MOUNTPOINT}/${DESTSITE}:/home/#{proxy.userId}/__ShinyStudio__:z"
        - '${MOUNTPOINT}/.rstudio/#{proxy.userId}/user-settings:/home/#{proxy.userId}/.rstudio/monitored/user-settings:z'
        - 'r_libraries:/r-libs'
      container-env:
        USER: "#{proxy.userId}"
        USERID: ${USERID}
      port: 8787
      access-groups: [ 'admins' ]
    - id: rstudioadmin
      display-name: RStudio
      description: Create interactive apps and docs RStudio (all content).
      container-image: shinystudio_rshiny_rstudio
      container-cmd: ["/start.sh", "rstudio"]
      container-network: shinystudio-net
      container-volumes:
        - "${MOUNTPOINT}:/home/#{proxy.userId}/__ShinyStudio__:z"
        - '${MOUNTPOINT}/.rstudio/#{proxy.userId}/user-settings:/home/#{proxy.userId}/.rstudio/monitored/user-settings:z'
        - 'r_libraries:/r-libs'
      container-env:
        USER: "#{proxy.userId}"
        USERID: ${USERID}
      port: 8787
      access-groups: [ 'superadmins' ]
